[[plugins]]
repo = 'morhetz/gruvbox.git'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/defx.nvim'

# status bar
[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
    let g:airline_powerline_fonts = 1
    let g:airline#extensions#tabline#enabled = 1
    set laststatus=2
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
    let g:airline_theme='minimalist'
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
depends = ['tiagofumo/vim-nerdtree-syntax-highlight']
hook_add = '''
    let g:NERDTreeShowHidden = 1
    let g:NERDTreeShowBookmarks=1
    autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
    autocmd StdinReadPre * let s:std_in=1
    autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
'''

[[plugins]]
repo = 'tiagofumo/vim-nerdtree-syntax-highlight'

# comment
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
    nmap <Leader>c <Plug>(caw:hatpos:toggle)
    vmap <Leader>c <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

# brackets
[[plugins]]
repo = 'itmammoth/doorboy.vim'

[[plugins]]
repo = 'machakann/vim-sandwich'

[[plugins]]
repo = 'bitc/lushtags'

[[plugins]]
repo = 'embear/vim-localvimrc'
hook_add = 'let g:localvimrc_ask = 0'

# for markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
depends = ['godlygeek/tabular']

[[plugins]]
repo = 'godlygeek/tabular'

# for latex
[[plugins]]
repo = 'lervag/vimtex'
hook_add = 'g:vimtex_compiler_progname = "nvr"'

[[plugins]]
repo = 'xuhdev/vim-latex-live-preview'

# for languages
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
    let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'racer-rust/vim-racer'

[[plugins]]
repo = 'alpicola/vim-egison'

[[plugins]]
repo = 'neovimhaskell/haskell-vim'

[[plugins]]
repo = 'andy-morris/alex.vim'

[[plugins]]
repo = 'andy-morris/happy.vim'

[[plugins]]
repo = 'cespare/vim-toml'
