[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  let g:neosnippet#snippets_directory='~/dotfiles/config/nvim/snippets/'
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_source = ['neosnippet']

# for markdown
[[plugins]]
repo = 'previm/previm'
on_ft = 'markdown'
hook_add = 'let g:previm_open_cmd = "google-chrome"'

# for latex
[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'latex'
hook_source = 'g:vimtex_compiler_progname = "nvr"'

[[plugins]]
repo = 'xuhdev/vim-latex-live-preview'
on_ft = 'latex'

# for languages
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
    let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'

[[plugins]]
repo = 'alpicola/vim-egison'
on_ft = 'egison'

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = 'haskell'

[[plugins]]
repo = 'andy-morris/alex.vim'
on_ft = 'alex'

[[plugins]]
repo = 'andy-morris/happy.vim'
on_ft = 'happy'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
