[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#disable_auto_complete = true
'''
on_i = 1

# for markdown
[[plugins]]
repo = 'previm/previm'
on_ft = 'markdown'
hook_add = 'let g:previm_open_cmd = "google-chrome"'

# for languages
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = '''
  let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'

[[plugins]]
repo = 'alpicola/vim-egison'
on_ft = 'egison'

[[plugins]]
repo = 'neovimhaskell/haskell-vim'
on_ft = 'haskell'

[[plugins]]
repo = 'andy-morris/alex.vim'
on_ft = 'alex'

[[plugins]]
repo = 'andy-morris/happy.vim'
on_ft = 'happy'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'leanprover/lean.vim'
on_ft = 'lean'

[[plugins]]
repo = 'lucas8/coquille'
on_ft = 'coq'
hook_source = '''
  au FileType coq call coquille#FNMapping()
  nnoremap <C-s> :CoqToCursor<CR>
'''

[[plugins]]
repo = 'let-def/vimbufsync'
on_source = ['coquille']

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_source = '''
  let g:vimtex_quickfix_open_on_warning = 0
  let g:tex_flavor='latex'
'''
