[[plugins]]
repo = 'Shougo/dein.vim'

# status bar
[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
    let g:airline_powerline_fonts = 1
    let g:airline#extensions#tabline#enabled = 1
    set laststatus=2
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
  let g:nord_uniform_status_lines = 0
  let g:airline_theme='nord'
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'embear/vim-localvimrc'
hook_add = 'let g:localvimrc_ask = 0'

# comment
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
    nmap <Leader>c <Plug>(caw:hatpos:toggle)
    vmap <Leader>c <Plug>(caw:hatpos:toggle)
'''

# brackets
[[plugins]]
repo = 'itmammoth/doorboy.vim'

[[plugins]]
repo = 'machakann/vim-sandwich'

# tmux
[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
hook_add = 'let g:tmux_navigator_save_on_switch = 1'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']
