[[plugins]]
repo = 'Shougo/dein.vim'

# status bar
[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
  let g:airline_powerline_fonts = 1
  let g:airline#extensions#tabline#enabled = 1
  set laststatus=2
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'nordtheme/vim'
hook_add = '''
  let g:nord_uniform_status_lines = 0
  let g:airline_theme='nord'
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'embear/vim-localvimrc'
hook_add = 'let g:localvimrc_ask = 0'

# comment
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = '''
  nmap <Leader>c <Plug>(caw:hatpos:toggle)
  vmap <Leader>c <Plug>(caw:hatpos:toggle)
'''

# brackets
[[plugins]]
repo = 'itmammoth/doorboy.vim' # auto completion

[[plugins]]
repo = 'machakann/vim-sandwich' # saiw(, sdb, sd(, srb(, sr"(

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['fzf']
hook_add = '''
  let g:fzf_layout = { 'down': '~30%' }
  nnoremap <silent> ,f :Files<CR>
  nnoremap <silent> ,g :GFiles<CR>
  nnoremap <silent> ,F :GFiles?<CR>
  nnoremap <silent> ,b :Buffers<CR>
  nnoremap <silent> ,l :BLines<CR>
  nnoremap <silent> ,L :Lines<CR>
  nnoremap <silent> ,h :History<CR>
  nnoremap <silent> ,m :Mark<CR>

  nnoremap <silent> <C-]> :call fzf#vim#tags(expand('<cword>'))<CR>
  let g:fzf_buffers_jump = 1
'''
